FROM golang:alpine

RUN apk update

WORKDIR /src/validation

COPY go.mod go.sum ./
RUN go get -d ./...

RUN go install github.com/cespare/reflex@latest

CMD ["reflex", "-c", "./services/validation/reflex.conf"]
