FROM golang:alpine

RUN apk update

WORKDIR /src/validation

COPY go.mod go.sum ./
RUN go mod download

RUN go get github.com/cespare/reflex

CMD ["reflex", "-c", "./services/validation/reflex.conf"]
