FROM golang:1.16-alpine

RUN apk update

WORKDIR /src/geoip

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/cespare/reflex@latest

CMD ["reflex", "-c", "./services/geoip/reflex.conf"]
