FROM golang:alpine as build

WORKDIR /src/parseschema
ADD . /src/parseschema
RUN CGO_ENABLED=0 go build -o /bin/parseschema ./services/cronjob/parseschema/cmd/parseschema

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
COPY --from=build /bin/parseschema /app/parseschema
EXPOSE 8000
CMD ["/app/parseschema"]
