FROM golang:alpine as build

WORKDIR /src/nodecleanup
ADD . /src/nodecleanup
RUN CGO_ENABLED=0 go build -o /bin/nodecleanup ./services/cronjob/nodecleanup/cmd/nodecleanup

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
COPY --from=build /bin/nodecleanup /app/nodecleanup
EXPOSE 8000
CMD ["/app/nodecleanup"]
