FROM golang:1.16-alpine as build

WORKDIR /src/nodecleaner
ADD . /src/nodecleaner
RUN CGO_ENABLED=0 go build -o /bin/nodecleaner ./services/cronjob/nodecleaner/cmd/nodecleaner

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
COPY --from=build /bin/nodecleaner /app/nodecleaner
EXPOSE 8000
CMD ["/app/nodecleaner"]
