FROM golang:1.19.5-alpine as build

WORKDIR /src/index
ADD . /src/index
RUN CGO_ENABLED=0 go build -o /bin/index ./services/index/cmd/index

FROM ubuntu:20.04

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
COPY --from=build /bin/index /app/index
EXPOSE 8000
CMD ["/app/index"]
