FROM golang:1.15-buster as build

ADD . /src/index
WORKDIR /src/index

# COPY go.mod .
# COPY go.sum .

RUN go get -v -t -d ./...
RUN go get github.com/cespare/reflex

CMD ["reflex", "-c", "./services/index/reflex.conf"]

# FROM golang:1.15-buster as build

# ADD . /src/index
# WORKDIR /src/index
# RUN go build -o /bin/index ./index/cmd/index

# FROM ubuntu:16.04

# RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
# COPY --from=build /bin/index /app/
# EXPOSE 8080
# ENTRYPOINT ["/app/index"]
# CMD ["serve"]
