{
 "title": "Logging",
 "tags": [ "logging" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Status 200",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\"} | json |= `Log Entry` | status=`200` [$__interval]))"
    }
   ]
  },
  {
   "title": "Status 404",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\"} | json |= `Log Entry` | status=`404` [$__interval]))"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\"} | json |= `Log Entry` | status=`500` [$__interval]))",
     "legendFormat": "Status 500"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"default\"} |= \"Log Entry\")[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(count_over_time(({namespace=\"default\"} | json |= \"Log Entry\" | status = `200`)[$__interval])) / sum(count_over_time(({namespace=\"default\"} |= \"Log Entry\")[$__interval]))) * 100",
     "legendFormat": "Status 200"
    },
    {
     "expr": "(sum(count_over_time(({namespace=\"default\"} | json |= \"Log Entry\" | status = `404`)[$__interval])) / \nsum(count_over_time(({namespace=\"default\"} |= \"Log Entry\")[$__interval]))) * 100",
     "legendFormat": "Status 404"
    },
    {
     "expr": "(sum(count_over_time(({namespace=\"default\"} | json |= \"Log Entry\" | status = `500`)[$__interval])) / \nsum(count_over_time(({namespace=\"default\"} |= \"Log Entry\")[$__interval]))) * 100",
     "legendFormat": "Status 500"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (ip, country, city) (count_over_time(({namespace=\"default\"} |= \"Log Entry\" | json)[$__interval]))"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"default\"} |~ \"err|error\""
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"default\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  }
 ]
}