{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isPretest := eq $env "pretest" }}
{{- $isTraefik := eq .Values.ingress.className "traefik" }}

{{- if $isTraefik }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: body-limit
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.ingress.maxBodyBytes | int64 }}
{{- if or $isProd $isStaging $isPretest }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
{{- end }}
