FROM golang:1.17.5-alpine

RUN apk update

WORKDIR /src/dataproxy

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/cespare/reflex@latest

CMD ["reflex", "-c", "./services/dataproxy/reflex.conf"]
