FROM golang:alpine

WORKDIR /src/nodecleanup

COPY go.mod .
COPY go.sum .

RUN go get -v -t -d ./...
RUN go get github.com/cespare/reflex

CMD ["go", "run", "services/cronjob/cmd/nodecleanup/main.go"]
