name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Execute Tests
        run: make test

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
            version: v1.56.1

  build:
    name: Build Docker Image - ${{ matrix.service }}
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - index
          - library
          - validation
          - dataproxy
          - nodecleaner
          - revalidatenode
          - schemaparser
          - dataproxyupdater
          - dataproxyrefresher
          - maintenance
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: DockerHub Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker Image
        run: make docker-push-${{ matrix.service }} DEPLOY_ENV=staging

  deploy:
    name: Deploy Services
    needs:
      - test
      - lint
      - build
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ secrets.TEST_SERVER_IP }}
      KUBECONFIG_PATH: ${{ secrets.KUBECONFIG_PATH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_ENV: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup SSH and Deploy Services
        run: ./scripts/deploy-services.sh

  e2e_test:
    name: E2E Test
    needs:
      - test
      - lint
      - build
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Test Index
        run: >
          ./scripts/wait_for_timeout.sh
          https://test-index.murmurations.network/v2/ping 200 300

      - name: Test Library
        run: >
          ./scripts/wait_for_timeout.sh
          https://test-library.murmurations.network/v2/ping 200 300

      - name: Test Data Proxy
        run: >
          ./scripts/wait_for_timeout.sh
          https://test-data-proxy.murmurations.network/v1/ping 200 300

      - name: Newman E2E Test
        run: make newman-test DEPLOY_ENV=staging
